FROM ubuntu:bind9
#image ubuntu

MAINTAINER Aurelle Awountsa <aawountsa@gmail.com>

#mise a jour image et installation de bind9 

RUN apt update && apt full-upgrade -y && \
    apt install bind9 bind9utils dnsutils net-tools nano -y

# activation IPv4:Modifie les options de configuration de BIND9 pour n'utiliser que l'IPv4 et pour exécuter le service en tant qu'utilisateur 'bind'.


RUN sed -i 's/OPTIONS=.*/OPTIONS="-4 -u bind"/' /etc/default/bind9

# copie des fichiers de configuration de la machine locale vers image docker

COPY named.conf /etc/bind/ 
COPY l2-8.ephec-ti.be /etc/bind/ 

#CREATION DU FICHIER DE LOG
RUN mkdir /var/log/named
RUN touch /var/log/named/misc.log /var/log/named/query.log
RUN chown -R root:bind /var/log/named


#ouverture du port 53 en udp de image
EXPOSE 53/tcp
EXPOSE 53/udp


WORKDIR /etc/bind

#demarrage du serveur dns 
CMD named -c /etc/bind/named.conf -g
