version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: web_cont
    hostname : web_cont
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html/:/var/www/html
    ports:
      - "80:80"
    restart: always


  php:
    image: php_img
    container_name: php_cont
    hostname: php_cont
    volumes:
      - ./html:/var/www/html


  db:
    image: mariadb
    container_name: db_cont
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: woodytoys
      MYSQL_USER: user
      MYSQL_PASSWORD: mypass
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./db/conf/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
